name: mrml-python

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/mrml-python-main.yml"
      - "Cargo.lock"
      - "Cargo.toml"
      - "packages/mrml-core/**"
      - "packages/mrml-python/**"
  pull_request:
    paths:
      - ".github/workflows/mrml-python-main.yml"
      - "Cargo.lock"
      - "Cargo.toml"
      - "packages/mrml-core/**"
      - "packages/mrml-python/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}-mrml-python
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      # Use deadsnakes until https://github.com/actions/setup-python/issues/771 is closed
      - name: Setup Python
        uses: deadsnakes/action@v3
        with:
          python-version: "3.13"
          nogil: true

      - name: install cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: init python venv
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv env
          source env/bin/activate
          python3 -m pip install pytest maturin
          maturin develop
          python3 -m pytest
        working-directory: packages/mrml-python
